name: Formatting
on: [push]
jobs:
  php-codesniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with Nova
        env:
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
          NOVA_API_TOKEN: ${{ secrets.NOVA_API_TOKEN }}
        run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_API_TOKEN}
      - name: Authenticate with Spark
        env:
          SPARK_USERNAME: ${{ secrets.SPARK_USERNAME }}
          SPARK_API_TOKEN: ${{ secrets.SPARK_API_TOKEN }}
        run: composer config http-basic.spark.laravel.com ${SPARK_USERNAME} ${SPARK_API_TOKEN}
      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --no-scripts
      - name: Run PHP CodeSniffer
        run: ./vendor/bin/phpcs --warning-severity=0
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint --ext=.js,.vue --quiet resources/js/
